# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN \
    dnf update -y && \
    dnf install -y gcc git python3 python3-libselinux python3-devel sudo curl which systemd && \
    dnf clean all && \
    useradd ansible-test-user

ENV SHELL /bin/bash
