---
dependency:
  name: galaxy
driver:
  name: docker
ansible:
  verbose: vv

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        unbound_enable_service: false
        unbound_reloaded_state: "stopped"

platforms:
  - name: ansible-ubuntu-16-04-lts
    image: ubuntu:16.04
  - name: ansible-ubuntu-18-04-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-lts
    image: ubuntu:20.04
  - name: ansible-debian
    image: debian:latest
  - name: ansible-arch
    image: archlinux/base:latest
    command: /usr/lib/systemd/systemd
    privileged: true
  - name: ansible-centos
    image: centos:latest
    command: /usr/lib/systemd/systemd
    privileged: true
  - name: ansible-almalinux
    image: almalinux:latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: ansible
