---
dependency:
  name: galaxy
driver:
  name: docker
ansible:
  verbose: vv

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        unbound_enable_service: false

platforms:
  - name: ansible-ubuntu-16-04-lts
    image: ubuntu
    image_version: '16.04'
  - name: ansible-ubuntu-1704
    image: ubuntu
    image_version: '17.04'
  - name: ansible-ubuntu-lts
    image: ubuntu
    image_version: '18.04'
  - name: ansible-arch
    image: archimg/base
    image_version: full
    command: /lib/systemd/systemd
    privileged: true
  - name: ansible-centos
    image: centos
    image_version: latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
